services:
  mongo:
    image: mongo:latest
    container_name: manul
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD-root}
    ports:
      - 27017:${MONGO_PORT-27017}
    volumes:
      - ./database-data:/data/db
